### ISSUE TITLE
你好,我是一个刚开始学习yii2的同学.有点问题想请教下

### ISSUE THREAD

**Issue by jonny77** [yiifans/lulucms#1]
我看了下你的框架
我现在想这样修改下框架
1:整个网站公用一个入口文件 index.php
2:我想把 视图/控制器的结构目录这样处理下

![Uploading 2014-11-03_170553.png . . .]()

我觉得这样处理的好处是结构目录清晰.model层完全可以供home/member/admin所有控制器公用了

有没有思路给个提示,或者给个demo...谢谢啦.

**Comment by jonny77** [comment]
![2014-11-03_170553](https://cloud.githubusercontent.com/assets/1962170/4880259/ef7b5018-6338-11e4-8730-6ca2d44856d2.png)

**Comment by yiifans** [comment]
也可以  没问题
现在yii2的控制器里面可以用子目录了
再好点你可以做成三个Module

models
   newsmodel.php
   usermodel.php
modules
   admin
        controllers
        views
   member
        ....
   home
        ....
