### ISSUE TITLE
如何设置是否需要用户登录啊

### ISSUE THREAD

**Issue by clark-wang** [yiifans/lulucms#2]
我看backend和frontend里面都有
“'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'loginUrl' => ['admin/login'],
        ],
”
只是frontend里面没有loginurl这个，但是为什么backend就要检查用户，需要登录，frontend就不需要用户登录，在哪里进行设置的啊

**Comment by Lynnworld** [comment]
https://github.com/yiifans/lulucms/blob/master/backend/base/BaseBackController.php 这里的behavior配置了登陆

**Comment by Tonkong** [comment]
hello ~ 
admin111的管理员登录密码是多少啊 admin111登不进去啊~

**Comment by yiifans** [comment]
因为现在前台还没有做用户相关的功能，所以目前前台不需要登录，也就不需要用户验证了。

**Comment by yiifans** [comment]
你是问的lu2的密码吗

**Comment by yiifans** [comment]
你是问的lu2的密码吗

**Comment by Tonkong** [comment]
是的 现在知道怎么改了 谢谢你的源码啊 ~
